---

pushgateway_version: "1.11.2"

pushgateway_system_user: pushgateway
pushgateway_system_group: pushgateway

pushgateway_direct_download: false

pushgateway_release: {}
pushgateway_service: {}

...
