---

- name: user and group handling
  when:
    - not running_in_check_mode
    - promscout_system_user != "root" or promscout_system_group != "root"
  block:
    - name: create promscout group
      ansible.builtin.group:
        name: "{{ promscout_system_group }}"
        state: present
        system: true
      when:
        - promscout_system_group != "root"

    - name: create promscout user
      ansible.builtin.user:
        name: "{{ promscout_system_user }}"
        groups: "{{ promscout_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent
      when:
        - promscout_system_user != "root"

- name: create install directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ promscout_install_path }}"
    state: directory
    owner: "{{ promscout_system_user }}"
    group: "{{ promscout_system_group }}"
    mode: 0755

- name: detect extracted binary file for promscout on '{{ promscout_delegate_to }}'
  when:
    - not running_in_check_mode
  become: false
  delegate_to: "{{ promscout_delegate_to }}"
  run_once: "{{ 'false' if promscout_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ promscout_local_tmp_directory }}/{{ promscout_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  when:
    - not running_in_check_mode
    - not stat_file_binary.stat.exists
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"

- name: detect installed promscout binary
  when:
    - not running_in_check_mode
  ansible.builtin.stat:
    path: "{{ promscout_install_path }}/{{ promscout_release.binary }}"
  register: stat_promscout_binary

- name: detect activated promscout binary
  when:
    - not running_in_check_mode
  ansible.builtin.stat:
    path: /usr/bin/{{ promscout_release.binary }}
  register: stat_promscout_activated

- name: install and activate promscout
  when:
    - not running_in_check_mode
    - stat_file_binary.stat.exists
    - (stat_promscout_binary.stat is defined and not stat_promscout_binary.stat.exists | default('false')) or
      not stat_promscout_activated.stat | bodsch.prometheus.linked_version(promscout_install_path, promscout_version)
  block:
    - name: propagate files
      block:
        - name: propagate promscout binaries
          ansible.builtin.copy:
            src: "{{ promscout_local_tmp_directory }}/{{ promscout_release.binary }}"
            dest: "{{ promscout_install_path }}/{{ promscout_release.binary }}"
            mode: 0755
            owner: "{{ promscout_system_user }}"
            group: "{{ promscout_system_group }}"
            remote_src: "{{ 'true' if promscout_direct_download else 'false' }}"

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ promscout_install_path }}/{{ promscout_release.binary }}"
            dest: "/usr/bin/{{ promscout_release.binary }}"
            state: link
            force: true
            follow: false
          notify:
            - restart promscout

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ promscout_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: create promscout configuration directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ promscout_config_dir }}"
    state: directory
    owner: root
    group: "{{ promscout_system_group }}"
    mode: 0770

- name: systemd
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create promscout system configuration
      ansible.builtin.template:
        src: "default/promscout.j2"
        dest: "{{ promscout_defaults_directory }}/promscout"
        force: true
        owner: root
        group: "{{ promscout_system_group }}"
        mode: 0640
      notify:
        - restart promscout

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/promscout.service.j2"
        dest: "{{ systemd_lib_directory }}/promscout.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload

- name: openrc
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/promscout.j2"
        dest: "/etc/conf.d/promscout"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/promscout.j2"
        dest: "/etc/init.d/promscout"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: promscout
    facts:
      version: "{{ promscout_version }}"

...
