---

redis_exporter_service:
  redis:
    address: ""                                                   # Address of the Redis instance to scrape (default "redis://localhost:6379")
    password: ""                                                  # Password of the Redis instance to scrape
    password_file: ""                                             # Password file of the Redis instance to scrape
    user: ""                                                      # User name to use for authentication (Redis ACL for Redis 6.0 and newer)
    only_metrics: ""                                              #
  check:
    key_groups: ""                                                # Comma separated list of lua regex for grouping keys
    keys: ""                                                      # Comma separated list of key-patterns to export value and length/size, searched for with SCAN
    keys_batch_size: ""                                           # Approximate number of keys to process in each execution, larger value speeds up scanning.
                                                                  # WARNING: Still Redis is a single-threaded app, huge COUNT can affect production environment. (default 1000)
    single_keys: []                                               # Comma separated list of single keys to export value and length/size
    single_streams: []                                            # Comma separated list of single streams to export info about streams, groups and consumers
    streams: []                                                   # Comma separated list of stream-patterns to export info about streams, groups and consumers, searched for with SCAN
  config_command: ""                                              #
  connection_timeout: ""                                          #
  count_keys: []                                                  #
  debug: ""                                                       #
  disable_exporting_key_values: ""                                #
  export_client_list: ""                                          #
  export_client_port: ""                                          #
  include_config_metrics: ""                                      #
  include_system_metrics: ""                                      #
  is_cluster: ""                                                  #
  is_tile38: ""                                                   #
  max_distinct_key_groups: ""                                     #
  namespace: ""                                                   #
  ping_on_connect: ""                                             #
  redact_config_metrics: ""                                       #
  script: ""                                                      #
  set_client_name: ""                                             # [true | false]
  tls:                                                            #
    skip_tls_verification: ""                                     # Whether to to skip TLS verification
    ca_cert_file: ""                                              # Name of the CA certificate file (including full path) if the server requires TLS client authentication
    client:
      cert_file: ""                                               # Name of the client certificate file (including full path) if the server requires TLS client authentication
      key_file: ""                                                # Name of the client key file (including full path) if the server requires TLS client authentication
    server:
      ca_cert_file: ""                                            # Name of the CA certificate file (including full path) if the web interface and telemetry should require TLS client authentication
      cert_file: ""                                               # Name of the server certificate file (including full path) if the web interface and telemetry should use TLS
      key_file: ""                                                # Name of the server key file (including full path) if the web interface and telemetry should use TLS
      min_version: ""                                             # Minimum TLS version that is acceptable by the web interface and telemetry when using TLS (default "TLS1.2")
  log:
    level: info                                                   # NOT USED (but why!?)
    format: ""                                                    #
  web:                                                            #
    listen_address: "127.0.0.1:9121"                              #
    telemetry_path: "/metrics"                                    #

...
