---

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  notify: restart logstream_exporter
  when:
    - ansible_facts.service_mgr == 'systemd'

- name: reload logstream exporter
  become: true
  ansible.builtin.service:
    name: logstream_exporter
    state: reloaded
  when:
    - not running_in_check_mode

- name: restart logstream exporter
  become: true
  ansible.builtin.service:
    name: logstream_exporter
    state: restarted
  when:
    - not running_in_check_mode

...
