---

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure blackbox_exporter is enabled on boot
  when:
    - not running_in_check_mode
  become: true
  ansible.builtin.service:
    name: blackbox_exporter
    enabled: true
    state: started

...
