---

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_facts.service_mgr | lower == "systemd"

- name: reload promscout
  become: true
  ansible.builtin.service:
    name: promscout
    state: reloaded
  when:
    - not running_in_check_mode

- name: restart promscout
  become: true
  ansible.builtin.service:
    name: promscout
    state: restarted
  when:
    - not running_in_check_mode

...
