---

logstream_exporter_version: latest

logstream_exporter_server:
  log_listen_address: "127.0.0.1:2212"
  log_transport: "udp"
  metrics_listen_address: "127.0.0.1:9212"
  read_timeout: "30s"
  line_max_bytes: 1048576

...
